global:
  scrape_interval: 14s

scrape_configs:
  - job_name: "pulse-cubrid"
    metrics_path: "/actuator/prometheus"
    static_configs:
      # Exporter host (db-exporter)
      - targets: ["172.31.202.25:8085"]

